# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DafuFruit' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DafuFruit

  target 'DafuFruitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DafuFruitUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AVOSCloud'               # 数据存储、短信、云引擎调用等基础服务模块
pod 'AVOSCloudIM'             # 实时通信模块
pod 'AVOSCloudCrashReporting' # 错误报告模块
pod 'AFNetworking', '~> 3.0'

end
